version: '3'
services:
  react_app:
    build:
      context: ./react_app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  flask_app:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
